#!/usr/bin/env bash

VERSION="$(grep -P -o '\d+\.\d+\.\d+' src/cli.dats)"
TOKEN="$(cat ~/.git-token)"

git tag "$VERSION"
git push origin --tags
git tag -d "$VERSION"
git push origin master

github-release release -s "$TOKEN" -u vmchale -r polyglot -t "$VERSION"
github-release upload -s "$TOKEN" -u vmchale -r polyglot -n poly-s390x-linux-gnu -f target/poly-s390x-linux-gnu -t "$VERSION"
github-release upload -s "$TOKEN" -u vmchale -r polyglot -n poly-arm-linux-gnueabihf -f target/poly-arm-linux-gnueabihf -t "$VERSION"
github-release upload -s "$TOKEN" -u vmchale -r polyglot -n poly-aarch64-linux-gnu -f target/poly-aarch64-linux-gnu -t "$VERSION"
github-release upload -s "$TOKEN" -u vmchale -r polyglot -n poly-powerpc-linux-gnu -f target/poly-powerpc-linux-gnu -t "$VERSION"
github-release upload -s "$TOKEN" -u vmchale -r polyglot -n poly-powerpc64-linux-gnu -f target/poly-powerpc64-linux-gnu -t "$VERSION"
github-release upload -s "$TOKEN" -u vmchale -r polyglot -n poly-powerpc64le-linux-gnu -f target/poly-powerpc64le-linux-gnu -t "$VERSION"
github-release upload -s "$TOKEN" -u vmchale -r polyglot -n poly-alpha-linux-gnu -f target/poly-alpha-linux-gnu -t "$VERSION"
github-release upload -s "$TOKEN" -u vmchale -r polyglot -n poly-mips-linux-gnu -f target/poly-mips-linux-gnu -t "$VERSION"
github-release upload -s "$TOKEN" -u vmchale -r polyglot -n poly-mipsel-linux-gnu -f target/poly-mipsel-linux-gnu -t "$VERSION"
github-release upload -s "$TOKEN" -u vmchale -r polyglot -n poly-mips64-linux-gnuabi64 -f target/poly-mips64-linux-gnuabi64 -t "$VERSION"
github-release upload -s "$TOKEN" -u vmchale -r polyglot -n poly-mips64el-linux-gnuabi64 -f target/poly-mips64el-linux-gnuabi64 -t "$VERSION"
github-release upload -s "$TOKEN" -u vmchale -r polyglot -n poly-i686-linux-gnu -f target/poly-i686-linux-gnu -t "$VERSION"
github-release upload -s "$TOKEN" -u vmchale -r polyglot -n poly-sh4-linux-gnu -f target/poly-sh4-linux-gnu -t "$VERSION"
github-release upload -s "$TOKEN" -u vmchale -r polyglot -n poly-riscv64-linux-gnu -f target/poly-riscv64-linux-gnu -t "$VERSION"
github-release upload -s "$TOKEN" -u vmchale -r polyglot -n poly-hppa-linux-gnu -f target/poly-hppa-linux-gnu -t "$VERSION"
github-release upload -s "$TOKEN" -u vmchale -r polyglot -n poly-arm-linux-gnueabi -f target/poly-arm-linux-gnueabi -t "$VERSION"
github-release upload -s "$TOKEN" -u vmchale -r polyglot -n poly.1 -f man/poly.1 -t "$VERSION"
github-release upload -s "$TOKEN" -u vmchale -r polyglot -n poly.usage -f compleat/poly.usage -t "$VERSION"
github-release upload -s "$TOKEN" -u vmchale -r polyglot -n polyglot.deb -f target/polyglot.deb -t "$VERSION"
