#!/usr/bin/env sh

set -ex pipefail

VERSION="$(grep -P -o '\d+\.\d+\.\d+' src/cli.dats)"
TOKEN="$(cat ~/.git-token)"

git tag "$VERSION"
git push origin --tags
git tag -d "$VERSION"
git push origin master

github-release release -s "$TOKEN" -u vmchale -r polyglot -t "$VERSION"

for PLATFORM in s390x-linux-gnu arm-linux-gnueabihf aarch64-linux-gnu powerpc-linux-gnu powerpc64-linux-gnu powerpc64le-linux-gnu alpha-linux-gnu mips-linux-gnu mipsel-linux-gnu mips64-linux-gnu mips64el-linux-gnu i686-linux-gnu sh4-linux-gnu riscv64-linux-gnu hppa-linux-gnu arm-linux-gnueabi
do
    github-release upload -s "$TOKEN" -u vmchale -r polyglot -n poly-"$PLATFORM" -f target/poly-"$PLATFORM" -t "$VERSION"
done

github-release upload -s "$TOKEN" -u vmchale -r polyglot -n poly.1 -f man/poly.1 -t "$VERSION"
github-release upload -s "$TOKEN" -u vmchale -r polyglot -n poly.usage -f compleat/poly.usage -t "$VERSION"
github-release upload -s "$TOKEN" -u vmchale -r polyglot -n polyglot.deb -f target/polyglot.deb -t "$VERSION"
